apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rclone-copy.fullname" . }}
  labels:
    {{- include "rclone-copy.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  {{- if not .Values.secretConfig }}
  rclone.conf: |
{{ .Values.rcloneConf | indent 4 }}
  {{- end }}
  include-pattern.conf: |
{{ .Values.includePattern | indent 4 }}
