{{- if or .Values.configPassword .Values.secretConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config-{{ include "rclone-copy.fullname" . }}
  labels:
    {{- include "rclone-copy.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
type: Opaque
data:
  {{- if .Values.configPassword }}
  password: {{ .Values.configPassword | b64enc }}
  {{- end }}
  {{- if .Values.secretConfig }}
  rclone.conf: {{ .Values.rcloneConf | b64enc }}
  {{- end }}
{{- end }}
