{{- if or .Values.configPassword .Values.secretConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-config-{{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.configPassword }}
  password: {{ .Values.configPassword | b64enc }}
  {{- end }}
  {{- if .Values.secretConfig }}
  rclone.conf: {{ .Values.rcloneConf | b64enc }}
  {{- end }}
{{- end }}
