apiVersion: v1
kind: Secret
metadata:
  name: rclone-config-{{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.configPassword }}
  password: {{ .Values.configPassword | b64enc }}
  {{- end }}
  rclone.conf: {{ .Values.rcloneConf | nindent 4 | b64enc }}
