name: Publish Helm Charts

on:
  push:

jobs:
  get-version:
    name: Get version from bumpversion
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current version from bumpversion
        id: get-version
        run: |
          version=$(cat .bumpversion.cfg | sed -nE 's/.*current_version = (.*)/\1/p')
          if [[ "${GITHUB_REF#refs/heads/}" != "main" && "${GITHUB_REF#refs/heads/}" != "master" ]]; then
            version="${version}-SNAPSHOT"
          fi
          echo $version
          echo "version=$version" >> $GITHUB_OUTPUT
        shell: bash

  call-workflow-passing-data:
    name: Publish Helm chart
    uses: bakdata/ci-templates/.github/workflows/helm-multi-release.yaml@tiedemann/fix-helm-publish
    needs: get-version
    with:
      charts-path: "./charts"
      subdirs: "['rclone-copy']"
      gh-pages-branch: gh-pages
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      github-username: ${{ secrets.GH_USERNAME }}
      github-email: ${{ secrets.GH_EMAIL }}
      github-token: ${{ secrets.GH_TOKEN }}
