name: Publish Helm Charts

on:
  push:

jobs:
  get-version:
    name: Get version from bumpversion
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bump2version
        run: |
          pipx install bump2version
        shell: bash

      - name: Get current version from bumpversion
        id: get-version
        run: |
          if [[ "$GITHUB_REF" =~ ^refs/tags/.* ]]; then
            version="$(sed -nE 's/.*current_version = (.*)/\1/p' < .bumpversion.cfg)"
          else
            bump2version --allow-dirty --no-tag --no-commit patch
            version="$(sed -nE 's/.*current_version = (.*)/\1/p' < .bumpversion.cfg)-SNAPSHOT"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
        shell: bash

  publish:
    name: Publish Helm chart
    uses: bakdata/ci-templates/.github/workflows/helm-multi-release.yaml@1.46.4
    needs: get-version
    with:
      charts-path: "./charts"
      subdirs: "['rclone-copy']"
      gh-pages-branch: gh-pages
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      github-username: ${{ secrets.GH_USERNAME }}
      github-email: ${{ secrets.GH_EMAIL }}
      github-token: ${{ secrets.GH_TOKEN }}
